name: Pipeline Cypress CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm ci

      - name: Verificar permissões dos scripts
        run: |
          chmod +x node_modules/.bin/cypress
          chmod -R 755 node_modules/cypress

      - name: Criar arquivo de ambiente (cypress.env.json)
        run: |
          echo '{
            "USUARIO_KABUM": "${{ secrets.USUARIO_KABUM }}",
            "SENHA_KABUM": "${{ secrets.SENHA_KABUM }}"
          }' > cypress.env.json

      - name: Rodar testes Cypress com Allure
        run: npm run cy:run:allure

      - name: Gerar relatório Allure
        if: always()
        run: npm run allure:generate

      - name: Upload do relatório Allure como artefato
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 30
